create external table if not exists c2dwh_silver.laptops (
	sku int,
	name string,
	price int,
	brand string,
	category string,
	rating double,
	reviews_count int,
	cpu string,
	cpu_cores int,
	cpu_threads int,
	cpu_speed_ghz double,
	cpu_speed_ghz_max double,
	gpu string,
	gpu_ram_gb int,
	gpu_type string,
	ram_gb int,
	ram_gb_max int,
	ram_type string,
	ram_bus_mhz int,
	disk_gb int,
	disk_gb_max int,
	disk_type string,
	webcam string,
	screen_panel string,
	screen_size_inch double,
	screen_tech string,
	screen_res string,
	screen_rate_hz int,
	screen_nits int,
	os string,
	battery_wh double,
	weight_kg double,
	material string,
	connectivity string,
	ports string,
	url string,
	release_year int,
	release_month int,
	updated_at timestamp
)
partitioned by (partition_date string)
stored as parquet
location 's3://crawling-to-dwh/silver/laptops/'
tblproperties ('parquet.compression' = 'SNAPPY');