create external table if not exists c2dwh_silver.phones (
	sku int,
	name string,
	price int,
	brand string,
	category string,
	rating double,
	reviews_count int,
	cpu string,
	cpu_speed_ghz_max double,
	gpu string,
	ram_gb double,
	storage_gb double,
	rear_cam_mp string,
	front_cam_mp string,
	screen_type string,
	screen_size_inch_main double,
	screen_size_inch_sub double,
	screen_res_main string,
	screen_res_sub string,
	screen_panel_main string,
	screen_panel_sub string,
	screen_rate_hz_main int,
	screen_rate_hz_sub int,
	screen_nits_main int,
	screen_nits_sub int,
	os string,
	water_resistant string,
	battery_mah int,
	charger_w double,
	weight_g double,
	material string,
	connectivity string,
	network_support string,
	ports string,
	url string,
	release_year int,
	release_month int,
	updated_at timestamp
)
partitioned by (date date)
stored as parquet
location 's3://crawling-to-dwh/silver/phones/'
tblproperties ('parquet.compression' = 'SNAPPY');