name: "dbt_c2dwh"
version: "1.0.0"

profile: "dbt_c2dwh"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_c2dwh:
    silver: # staging layer
      +materialized: incremental # upsert table every runs
      +file_format: parquet
      +tblproperties:
        parquet.compression: SNAPPY
        classification: parquet
      +schema: c2dwh_silver # database in athena

    gold:
      +materialized: table # recreate table every runs
      +file_format: parquet
      +tblproperties:
        parquet.compression: SNAPPY
        classification: parquet
      +schema: c2dwh_gold

    marts:
      +materialized: view # recreate view every runs
      +schema: c2dwh_gold
